import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider} from "@clerk/nextjs";
import Footer from "@/components/footer"

import Header from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JCRM Technology",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ClerkProvider appearance={{
          baseTheme:"dark"
        }}>
          
            <Header />
            <main className="min-h-screen">{children}</main>
           <Footer/>
        
        </ClerkProvider>
      </body>
    </html>
  );
}
